services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
